/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all books
         * @description Returns a list of all books.
         */
        get: operations["getBooks"];
        put?: never;
        /** Create a new book */
        post: operations["createBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique Book Identifier */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        /** Get a book by ID */
        get: operations["getBookById"];
        /** Update an existing book */
        put: operations["updateBook"];
        post?: never;
        /** Delete a book */
        delete: operations["deleteBook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Book: {
            /** @example 101 */
            id: number;
            /** @example Clean Code */
            title: string;
            /** @example Robert C. Martin */
            author: string;
            /** @example 9780132350884 */
            isbn: string;
            /** @example Software Engineering */
            genre: string;
            /** @example 2008 */
            publishedYear: number;
            /**
             * Format: double
             * @example 699.99
             */
            price: number;
            /** @example true */
            available: boolean;
            /**
             * Format: date-time
             * @example 2026-07-02T10:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-07-02T10:00:00Z
             */
            updatedAt: string;
        };
        CreateBookRequest: {
            title: string;
            author: string;
            isbn: string;
            genre: string;
            publishedYear: number;
            price: number;
            /** @default true */
            available: boolean;
        };
        UpdateBookRequest: {
            title?: string;
            author?: string;
            isbn?: string;
            genre?: string;
            publishedYear?: number;
            price?: number;
            available?: boolean;
        };
        ApiResponse: {
            /** @example true */
            success: boolean;
            /** @example Request processed successfully. */
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
        BookResponse: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["Book"];
        };
        BookListResponse: components["schemas"]["ApiResponse"] & {
            data?: components["schemas"]["Book"][];
        };
        ErrorResponse: {
            /** @example false */
            success: boolean;
            /** @example Validation failed. */
            message: string;
            /** Format: date-time */
            timestamp: string;
            error: {
                /** @example 400 */
                status: number;
                /** @example BAD_REQUEST */
                code: string;
                /** @example Title is required. */
                details: string;
            };
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Book not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unexpected server error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Unique Book Identifier */
        BookId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of books retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookListResponse"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    createBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookRequest"];
            };
        };
        responses: {
            /** @description Book created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getBookById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique Book Identifier */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique Book Identifier */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookRequest"];
            };
        };
        responses: {
            /** @description Book updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique Book Identifier */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
