/**
 * Generates a tiny static landing page for GitHub Pages.
 * We can't run an Express server on Pages, so we publish an HTML page
 * that documents the API + shows build metadata. The API's dist/ still
 * exists as a build artifact for a "real" deploy target (Azure, Render, etc.).
 *
 * Environment variables consumed (all optional, injected by CI):
 *   APP_VERSION, GIT_SHA, BUILD_TIME, GREETING
 */
const fs = require('node:fs');
const path = require('node:path');

const version = process.env.APP_VERSION || require('../package.json').version;
const sha = (process.env.GIT_SHA || 'local').slice(0, 7);
const buildTime = process.env.BUILD_TIME || new Date().toISOString();
const greeting = process.env.GREETING || 'Hello';

const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>hello-api \u2014 v${version}</title>
  <style>
    :root { color-scheme: light dark; }
    body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
    code, pre { background: rgba(127,127,127,0.15); padding: 0.15rem 0.35rem; border-radius: 4px; }
    pre { padding: 0.75rem; overflow-x: auto; }
    .meta { font-size: 0.9rem; opacity: 0.75; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 999px; background: #2da44e; color: #fff; font-size: 0.75rem; }
  </style>
</head>
<body>
  <h1>hello-api <span class="badge">live</span></h1>
  <p>${greeting}! This page is deployed automatically by GitHub Actions on every merge to <code>main</code>.</p>

  <h2>Build metadata</h2>
  <ul class="meta">
    <li><strong>Version:</strong> ${version}</li>
    <li><strong>Commit:</strong> ${sha}</li>
    <li><strong>Built at:</strong> ${buildTime}</li>
  </ul>

  <h2>API endpoints (when run locally)</h2>
  <pre>GET  /
GET  /add/:a/:b
GET  /multiply/:a/:b
GET  /divide/:a/:b</pre>

  <h2>Run it locally</h2>
  <pre>npm ci
npm run build
npm start
# then: curl http://localhost:3000/add/2/3</pre>

  <p class="meta">Generated by <code>scripts/build-page.js</code>.</p>
</body>
</html>
`;

const outDir = path.resolve(__dirname, '..', 'public');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'index.html'), html, 'utf8');
// eslint-disable-next-line no-console
console.log(`Wrote ${path.join(outDir, 'index.html')}`);
